apiVersion: v1
kind: Service
metadata:
  name: vet-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: vet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer